apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: main
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      
  ## Production in EKS
  ####################
  # type: ClusterIP
  # ports:
  #   - name: proxy-base
  #     port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: club-service
  namespace: main
spec:
  selector:
    app: club-portal
  type: ClusterIP
  ports:
    - name: http
      port: 9000
